name: 📺 Stream TS (Low Latency)

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Start Stream
        run: |
          VIDEO_URL="http://2980382.c28s.cc/3003126827/3432645201/1416017?token=ShoJV0NcEgMVCVdRAQIPCFUAAVwCAFJdVwYFVQ8MU10CDlRTAlIGCAEaSUEXREVVBwg6DFUXC1UHBAZWCQJOR0RLBERvXVQbDRpXWlwABAhUR0lHRVxcAREPAVEABFVXBQxQDxwWQFBTGl9BVQMOAldWUUcdF1QcR1BCCFlZPQFUTghVVRYKV0JUCU9GX1lvAgAIBF9RE14RBRJKGlwRFRMCD0NcWBwbVVEREQVEUhJcR1NUBwATSBFWXxNWQRAcEwJDeHwWHBtSQBEGCkNeXwhHX0dFRhNIEVxDOUpQERFDXQBbVUYSAxUIR09GXVZIOQYKC19QUhBaWl4VGg9AVBMUQ1tfWllNWEo6Ew1UFQpEVFRRCAMJXRFI"
          RTMP_URL="rtmp://vsu.okcdn.ru/input/14627505512044_15347102124652_nyms3w6t7u"

          while true; do
            ffmpeg \
              -hide_banner \
              -loglevel warning \
              -fflags nobuffer \
              -flags low_delay \
              -probesize 32 \
              -analyzeduration 0 \
              -thread_queue_size 8192 \
              -i "$VIDEO_URL" \
              -map 0:v \
              -c:v copy \
              -an \
              -flvflags no_duration_filesize \
              -f flv "$RTMP_URL"

            echo "Reconnecting..."
            sleep 3
          done
