name: Kick Stream - Fast Start

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Start Stream Immediately
        run: |
          ffmpeg -re -timeout 10000000 -i "http://virtualdbxv.com:8080/alwan6hd/index.m3u8" \
          -i "logo.png" -filter_complex \
          "[1:v]scale=iw*0.08:-1[logo];[0:v]eq=brightness=0.03:contrast=1.03:saturation=1.12[video];[video][logo]overlay=30:H-h-30" \
          -vcodec libx264 -preset veryfast -profile:v high -level 4.1 -pix_fmt yuv420p -g 50 \
          -b:v 3500k -maxrate 3500k -bufsize 8000k \
          -acodec copy -map_metadata -1 \
          -f flv "rtmps://fa723fc1b171.global-contribute.live-video.net/app/sk_us-west-2_nkUmjoCL69RM_UVo973GLbMzeCMunGLzNKWbFQJ7Hfb"

