name: Alwan stream - a81

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install FFmpeg (Latest)
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ffmpeg
          ffmpeg -version | head -1

      - name: Start Stream
        run: |
          RTMP_URL="rtmp://vsu.okcdn.ru/input/14627505512044_15347102124652_nyms3w6t7u"
          SOURCE_URL="http://g.mztk02.cc/ayham/ayham/1339213?token=ShN0YQ0JGlhBVEk9ShAWG04kBi5fWQJEC0E8WgsHJDJHQQQJQQQQQ1JHG0EQQQQQQQ0QQQ0UWwVQAVVQUwxNQ0QQQQQQQQxAWUcQAQQQQQQQRhVGQQQQQUcNUFJQDFFQBQQACEgSQQQQRw1BQQQHQQQQQEYcFAQQQQQQQQQQQQQQQQQQQRICDBYJW09EV1xnBQFUBV5SQw5HBkNJRAQQQRMLXEQIXB.RAAQxDEQdMVxpbRghcBwBDGEdUDhAITRMYEwsQdSESFEAGHUMGCEtbVw9GA0ZERUMYR14SOhRcEhVDVFNcAUIaWEFVFU9EVVNAPgdWCl5TAkAMQQQQRANDQBMdEFQQQQQQAQQQEQQQEAJDQQQQQQQQQ0dK"

          if [ ! -f "alwan.png" ]; then
            echo "false"
            exit 1
          fi

          FAIL_COUNT=0
          MAX_FAILS=10

          while [ $FAIL_COUNT -lt $MAX_FAILS ]; do
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo "▶ Starting stream | Attempt: $((FAIL_COUNT + 1))"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

            ffmpeg \
              -hide_banner \
              -loglevel warning \
              -stats \
              -reconnect 1 \
              -reconnect_at_eof 1 \
              -reconnect_streamed 1 \
              -reconnect_delay_max 10 \
              -timeout 15000000 \
              -fflags +discardcorrupt+genpts \
              -i "$SOURCE_URL" \
              -i "logoworld.png" \
              -filter_complex \
                "[1:v]scale=1920:1080:flags=lanczos[logo];
                 [0:v][logo]overlay=30:main_h-overlay_h-30:format=auto,format=yuv420p,setsar=1" \
              -c:v libx264 \
              -preset veryfast \
              -tune zerolatency \
              -profile:v high \
              -crf 20 \
              -b:v 4500k \
              -maxrate 5000k \
              -bufsize 9000k \
              -g 50 \
              -keyint_min 25 \
              -c:a aac \
              -b:a 128k \
              -ar 44100 \
              -ac 2 \
              -f flv \
              "$RTMP_URL"

            EXIT_CODE=$?
            echo "⚠ FFmpeg exited with code: $EXIT_CODE"

            if [ $EXIT_CODE -eq 0 ]; then
              echo "✅ ended"
              break
            else
              FAIL_COUNT=$((FAIL_COUNT + 1))
              WAIT=$((FAIL_COUNT * 3))
              [ $WAIT -gt 30 ] && WAIT=30
              echo "Reconnecting in ${WAIT}s... (Fail $FAIL_COUNT/$MAX_FAILS)"
              sleep $WAIT
            fi
          done

          if [ $FAIL_COUNT -ge $MAX_FAILS ]; then
            echo "❌ Exiting."
            exit 1
          fi
